export CPU_ARCH = cortex-m0plus
export CPU_FAM  = samd20

USEMODULE += pm_layered

export UNDEF += $(BINDIR)/pm_layered/pm.o

include $(RIOTCPU)/sam0_common/Makefile.include
include $(RIOTMAKE)/arch/cortexm.inc.mk
